name: perflow
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=23.2.1
  - cudatoolkit=11.7
  - pip:
    - numpy==1.24.3
    - einops==0.6.1
    - pillow==9.4.0
    - torch==2.0.0
    - torchvision==0.15.1
    - diffusers==0.24.0
    - controlnet-aux==0.0.7
    - accelerate==0.22.0
    - transformers==4.27.0
    - omegaconf==2.3.0
    - safetensors==0.3.2